### ISSUE TITLE
fake-backend.js

### ISSUE THREAD

**Issue by nirav2410** [cornflourblue/vue-vuex-registration-login-example#2]
In the page [fake-backend-js](http://jasonwatmore.com/post/2018/07/14/vue-vuex-user-registration-and-login-tutorial-example#fake-backend-js)
path is return as fake-backend.ts ( a typescript file) but in actual repo, it is js file.

**Comment by cornflourblue** [comment]
This was just a typo in the blog post (.ts instead of .js).

It's fixed now, thanks for pointing it out 👍
